---
apiVersion: v2
name: feature-kubernetes-manifests
description: Kubernetes Observability feature for gathering Kubernetes manifests.
type: application
sources:
  - https://github.com/grafana/k8s-monitoring-helm/tree/main/charts/k8s-monitoring/charts/feature-kubernetes-manifests
version: 1.0.0
appVersion: 1.0.0
maintainers:
  - email: pete.wall@grafana.com
    name: petewall
dependencies: []
