---
cluster:
  name: my-test-cluster

destinations:
  grafanaCloudMetrics:
    type: prometheus

pipelines:
  clusterMetrics:
    destination: grafanaCloudMetrics

  podLogs: {}

pipelineSynchronization:
  enabled: true   # Requires remoteConfiguration to be enabled

remoteConfiguration:
  enabled: true
  url: https://fleet.grafana.com
  auth:
    type: basic
    username: 123456
    password: glc_thisismypassword

collectors:
  alloy-one:
    type: alloy
    controller:
      type: daemonset

  alloy-metrics:
    type: alloy
    alloy:
      clustering:
        name: alloy-metrics
        enabled: true

    controller:
      type: statefulset
      replicas: 1


# -- Telemetry services are additional deployments that generate and synthesize telemetry data from the cluster.
telemetryServices:
  kube-state-metrics:
    deploy: true

  node-exporter:
    deploy: true

  windows-exporter:
    deploy: true

  kepler:
    deploy: true

  cloudCostExporter:
    deploy: true
