apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Certificate
metadata:
  name: ca-cert
  namespace: prometheus
spec:
  isCA: true
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Certificate
metadata:
  name: prometheus-ssl
  namespace: prometheus
spec:
  alternativeNames:
    - prometheus-server.prometheus.svc.cluster.local
  caRef:
    name: ca-cert
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Certificate
metadata:
  name: prometheus-workload-ssl
  namespace: prometheus
spec:
  alternativeNames:
    - prometheus-workload-server.prometheus.svc.cluster.local
  caRef:
    name: ca-cert
