---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus
  namespace: monitoring
type: Opaque
stringData:
  host: "https://prometheus-server.prometheus.svc.cluster.local:9090"
  username: "promuser"
  password: "prometheuspassword"
---
apiVersion: v1
kind: Secret
metadata:
  name: combined
  namespace: monitoring
type: Opaque
stringData:
  prom-host: "https://prometheus-server.prometheus.svc.cluster.local:9090"
  prom-username: "promuser"
  prom-password: "prometheuspassword"
  loki-host: "http://loki.loki.svc:3100"
  loki-tenantId: "1"
  loki-username: "loki"
  loki-password: "lokipassword"
  tempo-host: "http://tempo.tempo.svc:4318"
