# yamllint disable rule:comments-indentation
---
# -- Name override
# @section -- General settings
nameOverride: ""

# -- Full name override
# @section -- General settings
fullnameOverride: ""

global:
  # -- The specific platform for this cluster. Will enable compatibility for some platforms. Supported options: (empty) or "openshift".
  # @section -- Global Settings
  platform: ""

  # -- How frequently to scrape metrics.
  # @section -- Global Settings
  scrapeInterval: 60s

  # -- Sets the max_cache_size for every prometheus.relabel component. ([docs](https://grafana.com/docs/alloy/latest/reference/components/prometheus.relabel/#arguments))
  # This should be at least 2x-5x your largest scrape target or samples appended rate.
  # @section -- Global Settings
  maxCacheSize: 100000

beyla:
  # -- The configuration preset to use. Valid options are "application" or "network".
  # @section -- Beyla
  preset: application

  # -- How frequently to scrape metrics from Beyla.
  # Overrides metrics.scrapeInterval
  # @default -- 60s
  # @section -- Beyla
  scrapeInterval: ""

  # -- Label matchers used to select the Beyla pods for scraping metrics.
  # @section -- Beyla
  labelMatchers:
    app.kubernetes.io/name: beyla

  # -- Rule blocks to be added to the discovery.relabel component for Beyla.
  # These relabeling rules are applied pre-scrape against the targets from service discovery.
  # Before the scrape, any remaining target labels that start with __ (i.e. __meta_kubernetes*) are dropped.
  # ([docs](https://grafana.com/docs/alloy/latest/reference/components/discovery.relabel/#rule-block))
  # @section -- Beyla
  extraDiscoveryRules: ""

  # -- Rule blocks to be added to the prometheus.relabel component for Beyla. ([docs](https://grafana.com/docs/alloy/latest/reference/components/prometheus.relabel/#rule-block))
  # These relabeling rules are applied post-scrape against the metrics returned from the scraped target, no __meta* labels are present.
  # @section -- Beyla
  extraMetricProcessingRules: ""

  # Adjustments to the scraped metrics to filter the amount of data sent to storage.
  # @section -- Beyla
  metricsTuning:
    # -- Metrics to keep. Can use regular expressions.
    # @section -- Beyla
    includeMetrics: []
    # -- Metrics to drop. Can use regular expressions.
    # @section -- Beyla
    excludeMetrics: []

  # -- Sets the max_cache_size for the prometheus.relabel component for Beyla.
  # This should be at least 2x-5x your largest scrape target or samples appended rate.
  # ([docs](https://grafana.com/docs/alloy/latest/reference/components/prometheus.relabel/#arguments))
  # Overrides metrics.maxCacheSize
  # @default -- 100000
  # @section -- Beyla
  maxCacheSize:

  config:
    # @ignored -- This allows this chart to create the ConfigMap while also keeping the default name
    skipConfigMapCheck: true
    # @ignored -- This allows this chart to create the Beyla ConfigMap with required modifications
    create: false

    # -- The configuration for Grafana Beyla
    # Some sections will be set automatically, such as the cluster name.
    # Others will be modified depending on the value of beyla.preset.
    # @section -- Beyla
    data:
      attributes:
        kubernetes:
          enable: true
          # @ignored -- This will be replaced by the actual cluster name
          # cluster_name: ""
      internal_metrics:
        prometheus:
          # @ignored -- This will be replaced with service.targetPort below
          port: 9090
          path: /internal/metrics
      prometheus_export:
        # @ignored -- This will be replaced with service.targetPort below
        port: 9090
        path: /metrics
        features:
          - application
          - network
          - application_service_graph
          - application_span

      # @ignored -- If the Application Observability feature is enabled, and if there is an HTTP or gRPC receiver, the
      # endpoint will be set here.
      # otel_traces_export:
      #   endpoint: ""

  # -- The port number for the Beyla service.
  # @section -- Beyla
  service:
    targetPort: 9090

  # @ignored
  podAnnotations:
    k8s.grafana.com/job: default/beyla
    k8s.grafana.com/logs.job: integrations/beyla

  # @ignored -- Beyla can only install to Linux nodes
  nodeSelector:
    kubernetes.io/os: linux

# @ignore
deployAsConfigMap: false
