raw: |-
  The host energy metrics configuration requires a connection to Kepler
  Please enable the built-in deployment:
  telemetryServices:
    kepler:
      deploy: true
  Or, set the namespace and label selectors for an existing Kepler:
  hostMetrics:
    energyMetrics:
      namespace: kepler-namespace
      labelSelectors:
        app.kubernetes.io/name: kepler
