---
apiVersion: v2
name: telemetry-services
description: Additional Deployments to generate observability telemetry data
icon: https://raw.githubusercontent.com/grafana/grafana/main/public/img/grafana_icon.svg
sources:
  - https://github.com/grafana/k8s-monitoring-helm/tree/main/charts/k8s-monitoring/charts/telemetry-services
version: 1.0.0
appVersion: 1.0.0
maintainers:
  - email: pete.wall@grafana.com
    name: petewall
dependencies:
  - name: kepler
    version: 0.6.1
    repository: https://sustainable-computing-io.github.io/kepler-helm-chart
    condition: kepler.deploy
  - alias: node-exporter
    name: prometheus-node-exporter
    version: 4.51.1
    repository: https://prometheus-community.github.io/helm-charts
    condition: node-exporter.deploy
  - alias: windows-exporter
    name: prometheus-windows-exporter
    version: 0.12.3
    repository: https://prometheus-community.github.io/helm-charts
    condition: windows-exporter.deploy
  - name: kube-state-metrics
    version: 6.4.2
    repository: https://prometheus-community.github.io/helm-charts
    condition: kube-state-metrics.deploy
  - name: opencost
    version: 2.5.9
    repository: https://opencost.github.io/opencost-helm-chart
    condition: opencost.deploy
