---
cluster:
  name: openshift-cluster

global:
  platform: openshift

destinations:
  - name: prometheus
    type: prometheus
    url: http://prometheus.prometheus.svc:9090/api/v1/write

  - name: loki
    type: loki
    url: http://prometheus.prometheus.svc:9090/api/v1/write

clusterMetrics:
  enabled: true
  kube-state-metrics:
    namespace: openshift-monitoring
    labelMatchers:
      app.kubernetes.io/name: kube-state-metrics
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    service:
      scheme: https

hostMetrics:
  enabled: true
  linuxHosts:
    enabled: true
    namespace: openshift-monitoring
    labelMatchers:
      app.kubernetes.io/name: prometheus-node-exporter
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    scrapeSettings:
      scheme: https
  energyMetrics:
    enabled: true

telemetryServices:
  kepler:
    deploy: true

clusterEvents:
  enabled: true

podLogs:
  enabled: true

integrations:
  alloy:
    instances:
      - name: alloy
        labelSelectors:
          app.kubernetes.io/name: [alloy-metrics, alloy-singleton, alloy-logs]

alloy-metrics:
  enabled: true

alloy-singleton:
  enabled: true

alloy-logs:
  enabled: true
  global:
    podSecurityContext:
      seLinuxOptions:
        type: container_logreader_t
