---
cluster:
  name: postgresql-integration-test-cluster

destinations:
  - name: localPrometheus
    type: prometheus
    url: http://prometheus-server.prometheus.svc:9090/api/v1/write
  - name: localLoki
    type: loki
    url: http://loki.loki.svc:3100/loki/api/v1/push
    tenantId: "1"
    auth:
      type: basic
      username: loki
      password: lokipassword

integrations:
  postgresql:
    instances:
      - name: test-database
        exporter:
          dataSource:
            host: test-database-mysql.mysql.svc
            auth:
              usernameKey: user
              passwordKey: password
        secret:
          create: false
          name: test-database-pg-db-pguser-test-database-pg-db
          namespace: postgresql
        logs:
          enabled: true
          labelSelectors:
            app.kubernetes.io/instance: test-database-pg-db

podLogs:
  enabled: true

alloy-metrics:
  enabled: true

alloy-logs:
  enabled: true
