---
apiVersion: v2
name: feature-cost-metrics
description: Gathers Kubernetes Cost metrics
icon: https://raw.githubusercontent.com/grafana/grafana/main/public/img/grafana_icon.svg
sources:
  - https://github.com/grafana/k8s-monitoring-helm/tree/main/charts/k8s-monitoring/charts/feature-cost-metrics
version: 1.0.0
appVersion: 1.0.0
maintainers:
  - email: pete.wall@grafana.com
    name: petewall
dependencies: []
