---
name: Bump dependency "kepler" for Helm chart "k8s-monitoring-feature-cluster-metrics"
sources:
  kepler:
    name: Get latest "kepler" Helm chart version
    kind: helmchart
    spec:
      name: kepler
      url: https://sustainable-computing-io.github.io/kepler-helm-chart
      versionfilter:
        kind: semver
        pattern: '*'
conditions:
  kepler:
    name: Ensure Helm chart dependency "kepler" is specified
    kind: yaml
    spec:
      file: charts/k8s-monitoring-feature-cluster-metrics/Chart.yaml
      key: $.dependencies[3].name
      value: kepler
    disablesourceinput: true
targets:
  kepler:
    name: Bump Helm chart dependency "kepler" for Helm chart "k8s-monitoring-feature-cluster-metrics"
    kind: helmchart
    spec:
      file: Chart.yaml
      key: $.dependencies[3].version
      name: charts/k8s-monitoring-feature-cluster-metrics
      versionincrement: none
    sourceid: kepler
