---
cluster:
  name: global-private-image-registries-example-cluster

destinations:
  - name: prometheus
    type: prometheus
    url: http://prometheus.prometheus.svc:9090/api/v1/write

  - name: loki
    type: loki
    url: http://loki.loki.svc:3100/loki/api/v1/push

  - name: tempo
    type: otlp
    url: http://tempo.tempo.svc:3200/api/v1/metrics
    metrics: {enabled: false}
    logs: {enabled: false}
    traces: {enabled: true}
    processors:
      tailSampling:
        enabled: true
        policies:
          - name: always_sample-policy
            type: always_sample

# Dependent charts use two methods for global image registry and pull secrets
# so we need to define it both ways.
global:
  # Required for Alloy, Alloy Operator and Beyla
  image:
    registry: my.registry.com
    pullSecrets:
      - name: my-registry-creds

  # Required for kube-state-metrics, Node Exporter and Windows Exporter
  imageRegistry: my.registry.com
  imagePullSecrets:
    - name: my-registry-creds

clusterMetrics:
  enabled: true

costMetrics:
  enabled: true

hostMetrics:
  enabled: true
  energyMetrics:
    enabled: true
  linuxHosts:
    enabled: true
  windowsHosts:
    enabled: true

podLogs:
  enabled: true

applicationObservability:
  enabled: true
  receivers:
    otlp:
      http:
        enabled: true

alloy-metrics:
  enabled: true

alloy-logs:
  enabled: true

alloy-receiver:
  enabled: true

telemetryServices:
  # Kepler does not utilize the global image registry settings
  kepler:
    deploy: true
    image:
      repository: my.registry.com/sustainable_computing_io/kepler
    imagePullSecrets:
      - name: my-registry-creds

  # OpenCost does not utilize the global image registry settings
  opencost:
    imagePullSecrets:
      - name: my-registry-creds
    opencost:
      exporter:
        image:
          registry: my.registry.com

  kube-state-metrics:
    deploy: true
  node-exporter:
    deploy: true
  windows-exporter:
    deploy: true
