---
name: Bump dependency "alloy" for Helm chart "k8s-monitoring"
sources:
  alloy:
    name: Get latest "alloy" Helm chart version
    kind: helmchart
    spec:
      name: alloy
      url: https://grafana.github.io/helm-charts
      versionfilter:
        kind: semver
        pattern: '*'
conditions:
  alloy:
    name: Ensure Helm chart dependency "alloy" is specified
    kind: yaml
    spec:
      file: charts/k8s-monitoring/Chart.yaml
      key: $.dependencies[0].name
      value: alloy
    disablesourceinput: true
targets:
  alloy:
    name: Bump Helm chart dependency "alloy" for Helm chart "k8s-monitoring"
    kind: helmchart
    spec:
      file: Chart.yaml
      key: $.dependencies[0].version
      name: charts/k8s-monitoring
      versionincrement: none
    sourceid: alloy
  alloy-events:
    name: Bump Helm chart dependency "alloy-events" for Helm chart "k8s-monitoring"
    kind: helmchart
    spec:
      file: Chart.yaml
      key: $.dependencies[1].version
      name: charts/k8s-monitoring
      versionincrement: none
    sourceid: alloy
  alloy-logs:
    name: Bump Helm chart dependency "alloy-logs" for Helm chart "k8s-monitoring"
    kind: helmchart
    spec:
      file: Chart.yaml
      key: $.dependencies[2].version
      name: charts/k8s-monitoring
      versionincrement: none
    sourceid: alloy
  alloy-profiles:
    name: Bump Helm chart dependency "alloy-profiles" for Helm chart "k8s-monitoring"
    kind: helmchart
    spec:
      file: Chart.yaml
      key: $.dependencies[3].version
      name: charts/k8s-monitoring
      versionincrement: none
    sourceid: alloy
  alloy-rules:
    name: Bump Helm chart dependency "alloy-rules" for Helm chart "k8s-monitoring"
    kind: helmchart
    spec:
      file: Chart.yaml
      key: $.dependencies[4].version
      name: charts/k8s-monitoring
      versionincrement: none
    sourceid: alloy
