---
name: Bump dependency "beyla" for Helm chart "k8s-monitoring"
sources:
  beyla:
    name: Get latest "beyla" Helm chart version
    kind: helmchart
    spec:
      name: beyla
      url: https://grafana.github.io/helm-charts
      versionfilter:
        kind: semver
        pattern: '*'

conditions:
  beyla:
    name: Ensure Helm chart dependency "beyla" is specified
    kind: yaml
    spec:
      file: charts/k8s-monitoring-v1/Chart.yaml
      key: $.dependencies[10].name
      value: beyla
    disablesourceinput: true

targets:
  beyla:
    name: Bump Helm chart dependency "beyla" for Helm chart "k8s-monitoring"
    kind: helmchart
    spec:
      file: Chart.yaml
      key: $.dependencies[10].version
      name: charts/k8s-monitoring-v1
      versionincrement: none
    sourceid: beyla
