---
name: Bump dependency "kepler" for Helm chart "k8s-monitoring"
sources:
  kepler:
    name: Get latest "kepler" Helm chart version
    kind: helmchart
    spec:
      name: kepler
      url: https://sustainable-computing-io.github.io/kepler-helm-chart
      versionfilter:
        kind: semver
        pattern: '*'

conditions:
  kepler:
    name: Ensure Helm chart dependency "kepler" is specified
    kind: yaml
    spec:
      file: charts/k8s-monitoring/Chart.yaml
      key: $.dependencies[10].name
      value: kepler
    disablesourceinput: true

targets:
  kepler:
    name: Bump Helm chart dependency "kepler" for Helm chart "k8s-monitoring"
    kind: helmchart
    spec:
      file: Chart.yaml
      key: $.dependencies[10].version
      name: charts/k8s-monitoring
      versionincrement: none
    sourceid: kepler
