---
name: Bump dependency "kube-state-metrics" for Helm chart "k8s-monitoring"
sources:
  kube-state-metrics:
    name: Get latest "kube-state-metrics" Helm chart version
    kind: helmchart
    spec:
      name: kube-state-metrics
      url: https://prometheus-community.github.io/helm-charts
      versionfilter:
        kind: semver
        pattern: '*'
conditions:
  kube-state-metrics:
    name: Ensure Helm chart dependency "kube-state-metrics" is specified
    kind: yaml
    spec:
      file: charts/k8s-monitoring/Chart.yaml
      key: $.dependencies[5].name
      value: kube-state-metrics
    disablesourceinput: true
targets:
  kube-state-metrics:
    name: Bump Helm chart dependency "kube-state-metrics" for Helm chart "k8s-monitoring"
    kind: helmchart
    spec:
      file: Chart.yaml
      key: $.dependencies[5].version
      name: charts/k8s-monitoring
      versionincrement: none
    sourceid: kube-state-metrics
