---
name: Bump dependency "prometheus-node-exporter" for Helm chart "k8s-monitoring"
sources:
  prometheus-node-exporter:
    name: Get latest "prometheus-node-exporter" Helm chart version
    kind: helmchart
    spec:
      name: prometheus-node-exporter
      url: https://prometheus-community.github.io/helm-charts
      versionfilter:
        kind: semver
        pattern: '*'

conditions:
  prometheus-node-exporter:
    name: Ensure Helm chart dependency "prometheus-node-exporter" is specified
    kind: yaml
    spec:
      file: charts/k8s-monitoring-v1/Chart.yaml
      key: $.dependencies[5].name
      value: prometheus-node-exporter
    disablesourceinput: true

targets:
  prometheus-node-exporter:
    name: Bump Helm chart dependency "prometheus-node-exporter" for Helm chart "k8s-monitoring"
    kind: helmchart
    spec:
      file: Chart.yaml
      key: $.dependencies[5].version
      name: charts/k8s-monitoring-v1
      versionincrement: none
    sourceid: prometheus-node-exporter
