---
name: Bump dependency "prometheus-operator-crds" for Helm chart "k8s-monitoring"
sources:
  prometheus-operator-crds:
    name: Get latest "prometheus-operator-crds" Helm chart version
    kind: helmchart
    spec:
      name: prometheus-operator-crds
      url: https://prometheus-community.github.io/helm-charts
      versionfilter:
        kind: semver
        pattern: '*'
conditions:
  prometheus-operator-crds:
    name: Ensure Helm chart dependency "prometheus-operator-crds" is specified
    kind: yaml
    spec:
      file: charts/k8s-monitoring/Chart.yaml
      key: $.dependencies[7].name
      value: prometheus-operator-crds
    disablesourceinput: true
targets:
  prometheus-operator-crds:
    name: Bump Helm chart dependency "prometheus-operator-crds" for Helm chart "k8s-monitoring"
    kind: helmchart
    spec:
      file: Chart.yaml
      key: $.dependencies[7].version
      name: charts/k8s-monitoring
      versionincrement: none
    sourceid: prometheus-operator-crds
