---
name: Bump dependency "prometheus-windows-exporter" for Helm chart "k8s-monitoring"
sources:
  prometheus-windows-exporter:
    name: Get latest "prometheus-windows-exporter" Helm chart version
    kind: helmchart
    spec:
      name: prometheus-windows-exporter
      url: https://prometheus-community.github.io/helm-charts
      versionfilter:
        kind: semver
        pattern: '*'
conditions:
  prometheus-windows-exporter:
    name: Ensure Helm chart dependency "prometheus-windows-exporter" is specified
    kind: yaml
    spec:
      file: charts/k8s-monitoring/Chart.yaml
      key: $.dependencies[8].name
      value: prometheus-windows-exporter
    disablesourceinput: true
targets:
  prometheus-windows-exporter:
    name: Bump Helm chart dependency "prometheus-windows-exporter" for Helm chart "k8s-monitoring"
    kind: helmchart
    spec:
      file: Chart.yaml
      key: $.dependencies[8].version
      name: charts/k8s-monitoring
      versionincrement: none
    sourceid: prometheus-windows-exporter
