---
apiVersion: v2
name: feature-pod-logs-objects
description: Kubernetes Observability feature for gathering logs using PodLogs objects.
type: application
sources:
  - https://github.com/grafana/k8s-monitoring-helm/tree/main/charts/k8s-monitoring/charts/feature-pod-logs-objects
version: 1.0.0
appVersion: 1.0.0
maintainers:
  - email: pete.wall@grafana.com
    name: petewall
dependencies: []
