---
# The set of metrics from Istio required for the Istio integration
- envoy_cluster_upstream_cx_rx_bytes_total
- envoy_cluster_upstream_cx_tx_bytes_total
- galley_validation_failed
- galley_validation_passed
- go_memstats_heap_alloc_bytes
- go_memstats_heap_inuse_bytes
- go_memstats_heap_sys_bytes
- istio_agent_go_memstats_heap_alloc_bytes
- istio_agent_go_memstats_heap_inuse_bytes
- istio_agent_go_memstats_heap_sys_bytes
- istio_agent_process_cpu_seconds_total
- istio_agent_process_open_fds
- istio_agent_process_resident_memory_bytes
- istio_agent_process_virtual_memory_bytes
- istio_build
- istio_request_bytes_sum
- istio_request_duration_milliseconds_count
- istio_request_duration_milliseconds_sum
- istio_requests_total
- istio_response_bytes_sum
- istio_tcp_received_bytes_total
- istio_tcp_sent_bytes_total
- istiod_uptime_seconds
- pilot_conflict_inbound_listener
- pilot_conflict_outbound_listener_tcp_over_current_tcp
- pilot_info
- pilot_k8s_cfg_events
- pilot_total_xds_internal_errors
- pilot_total_xds_rejects
- pilot_xds_cds_reject
- pilot_xds_eds_reject
- pilot_xds_lds_reject
- pilot_xds_pushes
- pilot_xds_rds_reject
- pilot_xds_write_timeout
- process_cpu_seconds_total
- process_open_fds
- process_resident_memory_bytes
- process_virtual_memory_bytes
- sidecar_injection_failure_total
- sidecar_injection_success_total
