cluster:
  name: metrics-only-test

externalServices:
  prometheus:
    host: https://prometheus.example.com
    basicAuth:
      username: "12345"
      password: "It's a secret to everyone"

pod_logs:
  enabled: false

cluster_events:
  enabled: false
