---
apiVersion: v2
name: feature-annotation-autodiscovery
description: Gathers metrics automatically based on Kubernetes Pod and Service annotations
icon: https://raw.githubusercontent.com/grafana/grafana/main/public/img/grafana_icon.svg
sources:
  - https://github.com/grafana/k8s-monitoring-helm/tree/main/charts/k8s-monitoring/charts/feature-annotation-autodiscovery
version: 1.0.0
appVersion: 1.0.0
maintainers:
  - email: pete.wall@grafana.com
    name: petewall
dependencies: []
