---
apiVersion: v2
name: k8s-monitoring-feature-cluster-events
description: Gathers Kubernetes Events
icon: https://raw.githubusercontent.com/grafana/grafana/main/public/img/grafana_icon.svg
version: 1.0.0
appVersion: 1.0.0
dependencies: []
