# -- Name override
# @section -- General settings
nameOverride: ""

# -- Full name override
# @section -- General settings
fullnameOverride: ""

# -- List of namespaces to watch for events (`[]` means all namespaces)
# @section -- Gather settings
namespaces: []

# -- Log format used to forward cluster events. Allowed values: `logfmt` (default), `json`.
# @section -- Gather settings
logFormat: logfmt

# -- Stage blocks to be added to the loki.process component for cluster events.
# ([docs](https://grafana.com/docs/alloy/latest/reference/components/loki.process/#blocks))
# This value is templated so that you can refer to other values from this file.
# @section -- Processing settings
extraProcessingStages: ""

# @ignore
deployAsConfigMap: false
