apiVersion: v2
name: kubernetes-monitoring
description: A Helm chart for Kubernetes Monitoring
type: application

version: 0.0.1
appVersion: 1.1.5
icon: https://raw.githubusercontent.com/grafana/grafana/main/public/img/grafana_icon.svg
maintainers:
  - email: pete.wall@grafana.com
    name: petewall
dependencies:
- name: grafana-agent
  version: ~0.15.0
  repository: https://grafana.github.io/helm-charts
- name: kube-state-metrics
  version: ~5.8.0
  repository: https://prometheus-community.github.io/helm-charts
  condition: kube-state-metrics.enabled
- name: prometheus-node-exporter
  version: ~4.17.5
  repository: https://prometheus-community.github.io/helm-charts
  condition: prometheus-node-exporter.enabled
- name: prometheus-operator-crds
  version: ~4.0.2
  repository: https://prometheus-community.github.io/helm-charts
  condition: prometheus-operator-crds.enabled
- name: opencost
  version: ~1.15.0
  repository: https://opencost.github.io/opencost-helm-chart
  condition: opencost.enabled
