---
## Reference: https://github.com/helm/chart-testing/blob/master/doc/ct_lint-and-install.md
remote: origin
target-branch: main
chart-dirs:
  - charts
chart-repos:
  - grafana=https://grafana.github.io/helm-charts
  - kepler=https://sustainable-computing-io.github.io/kepler-helm-chart
  - opencost=https://opencost.github.io/opencost-helm-chart
  - prometheus-community=https://prometheus-community.github.io/helm-charts
validate-chart-schema: true
validate-maintainers: true
validate-yaml: true
exclude-deprecated: true
excluded-charts:
  - k8s-monitoring
