---
# -- Name for this DCGM Exporter instance.
# @section -- General Settings
name: ""

# -- The value of the job label for scraped metrics
# @section -- General Settings
jobLabel: integrations/dcgm-exporter

# -- Namespaces to look for DCGM Exporter instances in.
# Will automatically look for DCGM Exporter instances in all namespaces unless specified here
# @section -- Discovery Settings
namespaces: []

# -- Discover DCGM Exporter instances based on field selectors.
# @section -- Discovery Settings
fieldSelectors: []

# -- Discover DCGM Exporter instances based on label selectors. At least one is required.
# @section -- Discovery Settings
labelSelectors: {}

metrics:
  # -- Whether to enable metrics collection from DCGM Exporter.
  # @section -- Metrics Settings
  enabled: true

  # -- Name of the port to scrape metrics from.
  # @section -- Discovery Settings
  portName: metrics

  # -- How frequently to scrape metrics from DCGM Exporter.
  # @default -- `60s`
  # @section -- Scrape Settings
  scrapeInterval:

  # -- The timeout for scraping metrics from DCGM Exporter.
  # @default -- `10s`
  # @section -- Scrape Settings
  scrapeTimeout: ""

  tuning:
    # -- Metrics to keep. Can use regular expressions.
    # @section -- Metric Processing Settings
    includeMetrics: []
    # -- Metrics to drop. Can use regular expressions.
    # @section -- Metric Processing Settings
    excludeMetrics: []

  # -- Sets the max_cache_size for prometheus.relabel component.
  # This should be at least 2x-5x your largest scrape target or samples appended rate.
  # ([docs](https://grafana.com/docs/alloy/latest/reference/components/prometheus.relabel/#arguments))
  # Overrides global.maxCacheSize
  # @default -- `100000`
  # @section -- Metric Processing Settings
  maxCacheSize:
