{{- range $instance := .Values.postgresql.instances }}
  {{- $instance = merge $instance (dict "type" "integration.postgresql") }}
  {{- if eq (include "secrets.shouldCreateKubernetesSecret" $instance ) "true" }}
  {{- $values := mergeOverwrite (dict "object" $instance) $ }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.kubernetesSecretName" $values | quote }}
  namespace: {{ include "secrets.kubernetesSecretNamespace" $values | quote }}
stringData:
{{- $secrets := include "secrets.list.integration.postgresql" $instance | fromYamlArray }}
{{- range $secret := $secrets }}
  {{- $value := include "secrets.getSecretValue" (dict "object" $instance "key" $secret) -}}
  {{- if $value }}
  {{ include "secrets.getSecretKey" (dict "object" $instance "key" $secret) }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  {{- end -}}
{{- end -}}
