cluster:
  name: openshift-compatible-test
externalServices:
  prometheus:
    host: https://prometheus.example.com
    proxyURL: http://192.168.1.100:8080
    basicAuth:
      username: '12345'
      password: It's a secret to everyone
  loki:
    host: https://prometheus.example.com
    proxyURL: http://192.168.1.100:8080
    basicAuth:
      username: '12345'
      password: It's a secret to everyone
metrics:
  kube-state-metrics:
    service:
      port: https-main
      isTLS: true
  node-exporter:
    labelMatchers:
      app.kubernetes.io/name: node-exporter
    service:
      isTLS: true
kube-state-metrics:
  enabled: false
prometheus-node-exporter:
  enabled: false
grafana-agent:
  agent:
    listenPort: 8080
  enabled: false
grafana-agent-logs:
  enabled: false
opentelemetry-collector:
  enabled: true
opentelemetry-collector-logs:
  enabled: true
