cluster:
  name: logs-only-test

externalServices:
  loki:
    host: https://loki.example.com
    username: "12345"
    password: "It's a secret to everyone"

metrics:
  enabled: false

kube-state-metrics:
  enabled: false

prometheus-node-exporter:
  enabled: false

prometheus-windows-exporter:
  enabled: false

prometheus-operator-crds:
  enabled: false

opencost:
  enabled: false
