---
# -- Name override
# @section -- General settings
nameOverride: ""

# -- Full name override
# @section -- General settings
fullnameOverride: ""

# -- List of namespaces to watch for events (`[]` means all namespaces)
# @section -- Gather settings
namespaces: []

# -- List of namespaces to ignore events for.
# @section -- Gather settings
excludeNamespaces: []

# -- Log format used to forward cluster events. Allowed values: `logfmt` (default), `json`.
# @section -- Gather settings
logFormat: logfmt

# -- Stage blocks to be added to the loki.process component for cluster events.
# ([docs](https://grafana.com/docs/alloy/latest/reference/components/loki/loki.process/#blocks))
# This value is templated so that you can refer to other values from this file.
# @section -- Processing settings
extraLogProcessingStages: ""

# -- The list of labels to keep on the logs, all other pipeline labels will be dropped.
# @section -- Processing settings
labelsToKeep:
  - job
  - level
  - namespace
  - node
  - source

# -- The structured metadata mappings to set.
# To not set any structured metadata, set this to an empty object (e.g. `{}`)
# Format: `<key>: <extracted_key>`.
# Example:
# structuredMetadata:
#   component: component
#   kind: kind
#   name: name
# @section -- Processing settings
structuredMetadata: {}

# @ignore
deployAsConfigMap: false
