{{- if .Values.rules.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alloy.fullname" (index .Subcharts "alloy-rules") }}
  namespace: {{ .Release.Namespace }}
data:
  config.alloy: |-
    {{- include "alloyRulesConfig" . | trim | nindent 4 }}
{{- end }}
