apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana-agent.fullname" (index .Subcharts "grafana-agent") }}
  namespace: {{ .Release.Namespace }}
data:
  cluster_name: {{ required ".Values.cluster.name is a required value. Please set it and try again." .Values.cluster.name }}
  config.river: |-
{{- include "agent.config.cluster_name" . | indent 4}}

{{- include "agent.config.nodes" . | indent 4}}

{{- include "agent.config.pods" . | indent 4}}

{{- include "agent.config.services" . | indent 4}}

{{- if .Values.metrics.enabled }}
  {{- include "agent.config.agent" . | indent 4}}
  
  {{- if .Values.metrics.kubelet.enabled }}
    {{- include "agent.config.kubelet" . | indent 4}}
  {{- end }}

  {{- if .Values.metrics.cadvisor.enabled }}
    {{- include "agent.config.cadvisor" . | indent 4}}
  {{- end }}

  {{- if (index .Values.metrics "kube-state-metrics").enabled }}
    {{- include "agent.config.kube_state_metrics" . | indent 4}}
  {{- end }}

  {{- if (index .Values.metrics "node-exporter").enabled }}
    {{- include "agent.config.node_exporter" . | indent 4}}
  {{- end }}

  {{- if (index .Values.metrics "windows-exporter").enabled }}
    {{- include "agent.config.windows_exporter" . | indent 4}}
  {{- end }}

  {{- if .Values.metrics.cost.enabled }}
    {{- include "agent.config.opencost" . | indent 4}}
  {{- end }}

  {{- if .Values.metrics.podMonitors.enabled }}
    {{- include "agent.config.pod_monitors" . | indent 4}}
  {{- end }}

  {{- if .Values.metrics.serviceMonitors.enabled }}
    {{- include "agent.config.service_monitors" . | indent 4}}
  {{- end }}

  {{- include "agent.config.prometheus" . | indent 4 }}
  {{- end }}

  {{- if .Values.logs.enabled }}

  {{- if .Values.logs.pod_logs.enabled }}
    {{- include "agent.config.logs.pod_logs" . | indent 4}}
  {{- end }}

  {{- if .Values.logs.cluster_events.enabled }}
    {{- include "agent.config.logs.cluster_events" . | indent 4}}
  {{- end }}

  {{- include "agent.config.loki" . | indent 4 }}
{{- end }}

{{- if .Values.extraConfig }}
{{ .Values.extraConfig | indent 4 }}
{{ end }}
