---
cluster:
  name: private-image-registries-example-cluster

destinations:
  - name: prometheus
    type: prometheus
    url: http://prometheus.prometheus.svc:9090/api/v1/write

  - name: loki
    type: loki
    url: http://loki.loki.svc:3100/loki/api/v1/push

  - name: tempo
    type: otlp
    url: http://tempo.tempo.svc:3200/api/v1/metrics
    metrics: {enabled: false}
    logs: {enabled: false}
    traces: {enabled: true}
    processors:
      tailSampling:
        enabled: true
        policies:
          - name: always_sample-policy
            type: always_sample

clusterMetrics:
  enabled: true

costMetrics:
  enabled: true

hostMetrics:
  enabled: true
  energyMetrics:
    enabled: true
  linuxHosts:
    enabled: true
  windowsHosts:
    enabled: true

autoInstrumentation:
  enabled: true
  beyla:
    image:
      registry: my.registry.com
      repository: grafana/beyla
      pullSecrets:
        - name: my-registry-creds
    k8sCache:
      image:
        registry: my.registry.com
        repository: grafana/beyla-k8s-cache
        pullSecrets:
          - name: my-registry-creds


applicationObservability:
  enabled: true
  receivers:
    otlp:
      http:
        enabled: true

alloy-operator:
  image:
    registry: my.registry.com
    repository: grafana/alloy-operator
    pullSecrets:
      - name: my-registry-creds
  waitForAlloyRemoval:
    image:
      registry: my.registry.com
      repository: grafana/grafana/helm-chart-toolbox-kubectl
      pullSecrets:
        - name: my-registry-creds

alloy-metrics:
  enabled: true

alloy-receiver:
  enabled: true

collectorCommon:
  alloy:
    image:
      registry: my.registry.com
      repository: grafana/alloy
      pullSecrets:
        - name: my-registry-creds
    configReloader:
      image:
        registry: my.registry.com
        repository: prometheus-operator/prometheus-config-reloader

telemetryServices:
  kube-state-metrics:
    deploy: true
    image:
      registry: my.registry.com
      repository: kube-state-metrics/kube-state-metrics
    imagePullSecrets:
      - name: my-registry-creds

  node-exporter:
    deploy: true
    image:
      registry: my.registry.com
      repository: prometheus/node-exporter
    imagePullSecrets:
      - name: my-registry-creds

  windows-exporter:
    deploy: true
    image:
      registry: my.registry.com
      repository: prometheus-community/windows-exporter
    imagePullSecrets:
      - name: my-registry-creds

  opencost:
    deploy: true
    metricsSource: prometheus
    imagePullSecrets:
      - name: my-registry-creds
    opencost:
      exporter:
        defaultClusterId: private-image-registries-example-cluster
        image:
          registry: my.registry.com
          repository: opencost/opencost
      prometheus:
        external:
          url: http://prometheus.prometheus.svc:9090/api/v1/query

  kepler:
    deploy: true
    image:
      repository: my.registry.com/sustainable_computing_io/kepler
    imagePullSecrets:
      - name: my-registry-creds
