{{- define "kubernetes_monitoring.beyla.config" }}
{{- $valuesMap := .Values | toYaml | fromYaml -}}
{{- $beylaMap := $valuesMap -}}
{{- if hasKey $valuesMap "beyla" }}
  {{- $beylaMap = (dig "beyla" dict $valuesMap) -}}
{{- end }}
{{- $clusterName := dict "attributes" (dict "kubernetes" (dict "cluster_name" (dig "cluster" "name" "" $valuesMap))) }}
{{- $configData := dig "config" "data" dict $beylaMap -}}
{{- $preset := dict }}
{{- if and (eq (dig "preset" "" $beylaMap) "network") (not (hasKey $configData "network")) }}
  {{- $preset = dict "network" (dict "enable" true)}}
{{- end }}
{{- if and (eq (dig "preset" "" $beylaMap) "application") (not (hasKey $configData "discovery")) }}
  {{- $preset = dict "discovery" (dict "services" (list (dict "k8s_namespace" ".")))}}
{{- end }}
{{- $tracing := dict }}
{{- if dig "deliverTracesToApplicationObservability" false $beylaMap }}
  {{- $endpoint := "" }}
  {{- if dig "receivers" "grpc" "enabled" false $valuesMap }}
    {{- $endpoint = printf "http://%s-%s.%s.svc.cluster.local:%d" $.Release.Name "alloy" $.Release.Namespace (int (dig "receivers" "grpc" "port" 0 $valuesMap)) }}
  {{- else if dig "receivers" "http" "enabled" false $valuesMap }}
    {{- $endpoint = printf "http://%s-%s.%s.svc.cluster.local:%d" $.Release.Name "alloy" $.Release.Namespace (int (dig "receivers" "http" "port" 0 $valuesMap)) }}
  {{- end }}
  {{- if $endpoint }}
    {{- $tracing = dict "otel_traces_export" (dict "endpoint" $endpoint) }}
  {{- end }}
{{- end }}
{{- merge $configData $clusterName $preset $tracing | toYaml }}
{{- end }}

{{- if .Values.beyla.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "beyla.fullname" .Subcharts.beyla }}
  namespace: {{ include "beyla.namespace" .Subcharts.beyla }}
  labels:
    {{- include "beyla.labels" .Subcharts.beyla | nindent 4 }}
    app.kubernetes.io/component: config
  {{- with .Values.beyla.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  beyla-config.yml: |-
    {{- include "kubernetes_monitoring.beyla.config" . | nindent 4 }}
{{- end }}
