{{- if and .Values.traces.enabled .Values.externalServices.tempo.secret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubernetes_monitoring.traces_service.secret.name" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{ with .Values.externalServices.tempo }}
  {{ .hostKey }}: {{ required ".Values.externalServices.tempo.host is required to use traces. Please set it and try again." .host | b64enc | quote }}
{{- if .basicAuth.username }}
  {{ .basicAuth.usernameKey }}: {{ .basicAuth.username | toString | b64enc | quote }}
{{- end }}
{{- if .basicAuth.password }}
  {{ .basicAuth.passwordKey }}: {{ .basicAuth.password | toString | b64enc | quote }}
{{- end }}
{{- if .tenantId }}
  {{ .tenantIdKey }}: {{ .tenantId | toString | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
